---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluent-utility
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: confluent-utility # has to match .spec.template.metadata.labels
  serviceName: "confluent-utility"
  replicas: 1 # by default is 1
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: confluent-utility # has to match .spec.selector.matchLabels
    spec:
      serviceAccountName: confluent-utility
      terminationGracePeriodSeconds: 10
      containers:
        - name: utility
          image: justinrlee/confluent-utility:latest
          env:
            - name: CONFLUENT_CMF_URL
              value: http://cmf.${NAMESPACE}.svc.cluster.local
            - name: CONFLUENT_CMF_CERTIFICATE_AUTHORITY_PATH
              value: /root/certs/ca.crt
            - name: NAMESPACE
              value: ${NAMESPACE}
            - name: CMF_ENVIRONMENT_NAME
              value: ${FLINK_DEV_ENV_NAME}
            - name: FLINK_DEV_ENV_NAME
              value: ${FLINK_DEV_ENV_NAME}
            - name: FLINK_PROD_ENV_NAME
              value: ${FLINK_PROD_ENV_NAME}
            - name: VAULT_ADDR
              value: http://vault.vault.svc.cluster.local:8200
            - name: VAULT_TOKEN
              value: root
            - name: BS
              value: kafka.${NAMESPACE}.svc.cluster.local:9096
            - name: SR
              value: https://schemaregistry.${NAMESPACE}.svc.cluster.local:8081
            - name: KAFKA_OPTS
              value: "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token"
            - name: SCHEMA_REGISTRY_OPTS
              value: "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token"
            - name: TOKEN_ENDPOINT_URL
              value: http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token
            - name: CLIENT_ID
              value: ${CLIENT_ID}
            - name: CLIENT_SECRET
              value: ${CLIENT_SECRET}
            - name: SCOPE
              value: openid profile email
          volumeMounts:
            - name: client-tls
              readOnly: true
              mountPath: /root/certs
            - name: client-tls
              readOnly: true
              mountPath: /mnt/certs
            - name: utility-config
              readOnly: true
              mountPath: /root/config
            - name: utility-config
              readOnly: true
              mountPath: /root/tls.properties
              subPath: tls.properties
            - name: utility-config
              readOnly: true
              mountPath: /root/client.properties
              subPath: client.properties
            - name: utility-governance-config
              readOnly: true
              mountPath: /root/governance
            - name: utility-pipeline-config
              readOnly: true
              mountPath: /root/pipeline
            - name: utility-bin-config
              readOnly: true
              mountPath: /root/bin
            - name: governance-application-manifests
              readOnly: true
              mountPath: /root/governance/applications
      volumes:
        - name: client-tls
          secret:
            secretName: tls-client
        - name: utility-config
          configMap:
            name: utility-config
        - name: utility-governance-config
          configMap:
            name: utility-governance-config
        - name: utility-pipeline-config
          configMap:
            name: utility-pipeline-config
        - name: utility-bin-config
          configMap:
            name: utility-bin-config
            defaultMode: 0755
        - name: governance-application-manifests
          configMap:
            name: governance-application-manifests
